import { useEffect, useState } from 'react';
import { AppTopBar } from '../../components/AppTopBar';
import { useLiveQuery } from 'dexie-react-hooks';
import { db } from '../../db/database';
import { abandonSession, commitRound, introduceFounders, listGameRounds, startGameSession } from '../../breeding/game';
import { TRAITS } from '../../breeding/simulator';
import type { GameRound, TraitCode } from '../../breeding/types';
import {
  CartesianGrid,
  Legend,
  Line,
  LineChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from 'recharts';

export function GameScreen() {
  const lines = useLiveQuery(() => db.lines.toArray()) ?? [];
  const activeSession = useLiveQuery(async () => {
    const all = await db.gameSessions.where('status').equals('active').toArray();
    return all[0] ?? null;
  });
  const rounds = useLiveQuery(
    async () => (activeSession ? listGameRounds(activeSession.id) : []),
    [activeSession?.id],
  );
  const [lineId, setLineId] = useState<string>('');
  const [nMatings, setNMatings] = useState(40);
  const [inbreedingCeiling, setInbreedingCeiling] = useState(0.0625);
  const [weights, setWeights] = useState<Record<TraitCode, number>>(() => {
    const o: Record<TraitCode, number> = {} as Record<TraitCode, number>;
    for (const t of TRAITS) o[t.code] = t.economicWeight;
    return o;
  });
  const [busy, setBusy] = useState<'starting' | 'committing' | 'abandoning' | 'introducing' | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [foundersToAdd, setFoundersToAdd] = useState(50);
  const [interventionMsg, setInterventionMsg] = useState<string | null>(null);

  useEffect(() => {
    if (!lineId && lines.length > 0) setLineId(lines[0].id);
  }, [lines, lineId]);

  const handleStart = async () => {
    setBusy('starting');
    setError(null);
    try {
      await startGameSession({
        startedBy: localStorage.getItem('operator_name') ?? 'guest',
        config: { nMatings, inbreedingCeiling, economicWeights: weights },
      });
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setBusy(null);
    }
  };

  const handleCommit = async () => {
    if (!activeSession || !lineId) return;
    setBusy('committing');
    setError(null);
    try {
      await commitRound({
        sessionId: activeSession.id,
        lineId,
        weights,
        inbreedingCeiling,
        nMatings,
      });
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setBusy(null);
    }
  };

  const handleAbandon = async () => {
    if (!activeSession) return;
    if (!confirm('Abandon this session? All offspring generated by the game will be deleted.')) return;
    setBusy('abandoning');
    try {
      await abandonSession(activeSession.id);
    } finally {
      setBusy(null);
    }
  };

  const handleIntroduce = async () => {
    if (!activeSession) return;
    setBusy('introducing');
    setError(null);
    setInterventionMsg(null);
    try {
      const r = await introduceFounders(activeSession.id, foundersToAdd);
      setInterventionMsg(`Added ${r.added} outside founders to your pool. They have unknown EBVs and zero kinship — fresh diversity for the next round.`);
    } catch (e) {
      setError((e as Error).message);
    } finally {
      setBusy(null);
    }
  };

  return (
    <div className="flex h-dvh flex-col bg-gray-50">
      <AppTopBar />
      <div className="flex-1 overflow-y-auto p-4">
        <h1 className="mb-2 text-lg font-bold">Breeding Game</h1>
        <p className="mb-4 text-xs text-gray-600">
          Run the program for a few generations, configure your selection strategy, and see how
          you compare to the autonomous AI on identical data, and to the Oracle that knows the
          true breeding values. Larger gap to Oracle = information limit; smaller gap to Oracle =
          your strategy is approaching the theoretical ceiling.
        </p>

        {!activeSession && (
          <div className="rounded-xl bg-white p-4 shadow-sm">
            <h2 className="mb-2 text-sm font-semibold">Start a new session</h2>
            <Strategy
              lines={lines}
              lineId={lineId}
              setLineId={setLineId}
              nMatings={nMatings}
              setNMatings={setNMatings}
              inbreedingCeiling={inbreedingCeiling}
              setInbreedingCeiling={setInbreedingCeiling}
              weights={weights}
              setWeights={setWeights}
            />
            <button
              disabled={busy !== null}
              onClick={handleStart}
              className="mt-3 w-full rounded-md bg-indigo-600 py-2.5 text-sm font-semibold text-white disabled:opacity-60"
            >
              {busy === 'starting' ? 'Starting…' : 'Start session'}
            </button>
            {error && <p className="mt-2 text-xs text-red-600">{error}</p>}
          </div>
        )}

        {activeSession && (
          <>
            <div className="mb-3 flex items-center justify-between rounded-xl bg-gradient-to-br from-indigo-600 to-blue-500 p-3 text-white shadow">
              <div>
                <p className="text-xs opacity-80">Active session · started by {activeSession.startedBy}</p>
                <p className="text-sm font-semibold">
                  {(rounds?.length ?? 0)} rounds played from G{activeSession.startGeneration}
                </p>
              </div>
              <button
                onClick={handleAbandon}
                disabled={busy !== null}
                className="rounded-md bg-white/15 px-3 py-1.5 text-xs font-semibold text-white hover:bg-white/25 disabled:opacity-60"
              >
                {busy === 'abandoning' ? '…' : 'Abandon'}
              </button>
            </div>

            <div className="mb-3 rounded-xl bg-white p-4 shadow-sm">
              <h2 className="mb-2 text-sm font-semibold">Round strategy</h2>
              <Strategy
                lines={lines}
                lineId={lineId}
                setLineId={setLineId}
                nMatings={nMatings}
                setNMatings={setNMatings}
                inbreedingCeiling={inbreedingCeiling}
                setInbreedingCeiling={setInbreedingCeiling}
                weights={weights}
                setWeights={setWeights}
              />
              <button
                disabled={busy !== null || !lineId}
                onClick={handleCommit}
                className="mt-3 w-full rounded-md bg-emerald-600 py-2.5 text-sm font-semibold text-white disabled:opacity-60"
              >
                {busy === 'committing' ? 'Simulating round…' : `Commit round ${(rounds?.length ?? 0) + 1}`}
              </button>
              {error && <p className="mt-2 text-xs text-red-600">{error}</p>}
            </div>

            {rounds && rounds.length > 0 && (
              <div className="mb-3 rounded-xl bg-white p-4 shadow-sm">
                <h2 className="mb-2 text-sm font-semibold">Interventions</h2>
                <p className="text-xs text-gray-600">
                  Drop fresh founders into your pool — zero kinship, unknown EBVs, average TBV.
                  Trades short-term gain for diversity. Use when ΔF is climbing.
                </p>
                <div className="mt-2 flex items-center gap-2">
                  <input
                    type="number"
                    min={5}
                    max={300}
                    value={foundersToAdd}
                    onChange={(e) => setFoundersToAdd(Number(e.target.value))}
                    className="w-24 rounded-md border border-gray-300 px-2 py-1 text-sm tabular-nums"
                  />
                  <button
                    disabled={busy !== null}
                    onClick={handleIntroduce}
                    className="rounded-md bg-amber-500 px-3 py-1.5 text-xs font-semibold text-white disabled:opacity-60"
                  >
                    {busy === 'introducing' ? 'Adding…' : `Introduce ${foundersToAdd} outside founders`}
                  </button>
                </div>
                {interventionMsg && (
                  <p className="mt-2 rounded-md bg-emerald-50 p-2 text-[11px] text-emerald-800">{interventionMsg}</p>
                )}
              </div>
            )}

            {rounds && rounds.length > 0 && <Scoreboard rounds={rounds} />}
          </>
        )}
      </div>
    </div>
  );
}

function Strategy(props: {
  lines: { id: string; name: string }[];
  lineId: string;
  setLineId: (s: string) => void;
  nMatings: number;
  setNMatings: (n: number) => void;
  inbreedingCeiling: number;
  setInbreedingCeiling: (n: number) => void;
  weights: Record<TraitCode, number>;
  setWeights: (w: Record<TraitCode, number>) => void;
}) {
  return (
    <>
      <div className="grid grid-cols-3 gap-2">
        <div>
          <label className="text-xs text-gray-500">Line</label>
          <select
            value={props.lineId}
            onChange={(e) => props.setLineId(e.target.value)}
            className="mt-0.5 w-full rounded-md border border-gray-300 px-2 py-1 text-sm"
          >
            {props.lines.map((l) => (
              <option key={l.id} value={l.id}>{l.id}</option>
            ))}
          </select>
        </div>
        <div>
          <label className="text-xs text-gray-500">Mating slots</label>
          <input
            type="number"
            value={props.nMatings}
            onChange={(e) => props.setNMatings(Number(e.target.value))}
            className="mt-0.5 w-full rounded-md border border-gray-300 px-2 py-1 text-sm tabular-nums"
          />
        </div>
        <div>
          <label className="text-xs text-gray-500">F ceiling</label>
          <input
            type="number"
            step="0.005"
            value={props.inbreedingCeiling}
            onChange={(e) => props.setInbreedingCeiling(Number(e.target.value))}
            className="mt-0.5 w-full rounded-md border border-gray-300 px-2 py-1 text-sm tabular-nums"
          />
        </div>
      </div>
      <div className="mt-3">
        <label className="text-xs text-gray-500">Economic weights ($/unit)</label>
        <div className="mt-1 grid grid-cols-3 gap-2">
          {TRAITS.map((t) => (
            <div key={t.code}>
              <span className="block text-[11px] text-gray-500">
                {t.code} <span className="text-[10px] text-gray-400">·{t.unit}</span>
              </span>
              <input
                type="number"
                step="0.01"
                value={props.weights[t.code]}
                onChange={(e) =>
                  props.setWeights({ ...props.weights, [t.code]: Number(e.target.value) })
                }
                className="w-full rounded-md border border-gray-300 px-2 py-1 text-sm tabular-nums"
              />
            </div>
          ))}
        </div>
      </div>
    </>
  );
}

function Scoreboard({ rounds }: { rounds: GameRound[] }) {
  const data = rounds.map((_r, i) => ({
    round: i + 1,
    Player: cumulative(rounds, i, 'player'),
    AI: cumulative(rounds, i, 'ai'),
    Oracle: cumulative(rounds, i, 'oracle'),
  }));
  const fData = rounds.map((r, i) => ({
    round: i + 1,
    Player: r.player.meanF,
    AI: r.ai.meanF,
    Oracle: r.oracle.meanF,
  }));
  const last = rounds[rounds.length - 1];
  const totalPlayer = cumulative(rounds, rounds.length - 1, 'player');
  const totalAi = cumulative(rounds, rounds.length - 1, 'ai');
  const totalOracle = cumulative(rounds, rounds.length - 1, 'oracle');
  return (
    <>
      <div className="mb-3 grid grid-cols-3 gap-2">
        <Score label="You" v={totalPlayer} colour="text-indigo-600" />
        <Score label="AI" v={totalAi} colour="text-emerald-600" />
        <Score label="Oracle" v={totalOracle} colour="text-amber-600" />
      </div>
      <div className="rounded-xl bg-white p-3 shadow-sm">
        <div className="mb-2 text-xs uppercase tracking-wide text-gray-500">Cumulative realised mid-parent index ($)</div>
        <div className="h-56">
          <ResponsiveContainer width="100%" height="100%">
            <LineChart data={data}>
              <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
              <XAxis dataKey="round" tickFormatter={(v) => 'R' + v} />
              <YAxis tickFormatter={(v) => '$' + Number(v).toFixed(1)} />
              <Tooltip formatter={(v) => (typeof v === 'number' ? '$' + v.toFixed(2) : String(v))} />
              <Legend />
              <Line type="monotone" dataKey="Player" stroke="#4f46e5" strokeWidth={2} />
              <Line type="monotone" dataKey="AI" stroke="#10b981" strokeWidth={2} />
              <Line type="monotone" dataKey="Oracle" stroke="#f59e0b" strokeWidth={2} strokeDasharray="6 3" />
            </LineChart>
          </ResponsiveContainer>
        </div>
      </div>

      <div className="mt-3 rounded-xl bg-white p-3 shadow-sm">
        <div className="mb-2 text-xs uppercase tracking-wide text-gray-500">Mean offspring inbreeding F per round</div>
        <div className="h-48">
          <ResponsiveContainer width="100%" height="100%">
            <LineChart data={fData}>
              <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
              <XAxis dataKey="round" tickFormatter={(v) => 'R' + v} />
              <YAxis tickFormatter={(v) => Number(v).toFixed(3)} />
              <Tooltip formatter={(v) => (typeof v === 'number' ? v.toFixed(4) : String(v))} />
              <Legend />
              <Line type="monotone" dataKey="Player" stroke="#4f46e5" strokeWidth={2} />
              <Line type="monotone" dataKey="AI" stroke="#10b981" strokeWidth={2} />
              <Line type="monotone" dataKey="Oracle" stroke="#f59e0b" strokeWidth={2} strokeDasharray="6 3" />
            </LineChart>
          </ResponsiveContainer>
        </div>
      </div>

      <TraitTrajectories rounds={rounds} />
      <TraitDeltas rounds={rounds} />

      <div className="mt-3 rounded-xl bg-white p-3 shadow-sm">
        <div className="mb-2 text-xs uppercase tracking-wide text-gray-500">Round breakdown</div>
        <table className="w-full text-sm">
          <thead className="text-xs uppercase tracking-wide text-gray-500">
            <tr>
              <th className="py-1 text-left">Round</th>
              <th className="py-1 text-right">You ($)</th>
              <th className="py-1 text-right">AI ($)</th>
              <th className="py-1 text-right">Oracle ($)</th>
              <th className="py-1 text-right">Your F</th>
              <th className="py-1 text-right">Calibration</th>
            </tr>
          </thead>
          <tbody>
            {rounds.map((r, i) => {
              const calib = r.player.meanPredictedIndex - r.player.meanTrueIndex;
              return (
                <tr key={r.id} className="border-t border-gray-100">
                  <td className="py-1.5">R{i + 1}</td>
                  <td className="py-1.5 text-right tabular-nums">{r.player.meanTrueIndex.toFixed(2)}</td>
                  <td className="py-1.5 text-right tabular-nums">{r.ai.meanTrueIndex.toFixed(2)}</td>
                  <td className="py-1.5 text-right tabular-nums">{r.oracle.meanTrueIndex.toFixed(2)}</td>
                  <td className="py-1.5 text-right tabular-nums">{r.player.meanF.toFixed(4)}</td>
                  <td className={`py-1.5 text-right tabular-nums ${Math.abs(calib) > 1 ? 'text-amber-700' : 'text-gray-600'}`}>
                    {calib >= 0 ? '+' : ''}{calib.toFixed(2)}
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
        <p className="mt-2 text-[11px] text-gray-500">
          Calibration = predicted − realised. Close to zero is a well-calibrated index;
          large positive = optimism (your EBVs are over-predicting).
        </p>
      </div>

      {last.feedback.length > 0 && (
        <div className="mt-3 rounded-xl bg-amber-50 p-3 shadow-sm">
          <div className="mb-1 text-xs font-semibold uppercase tracking-wide text-amber-800">
            Coach notes — round {rounds.length}
          </div>
          <ul className="ml-4 list-disc space-y-1 text-xs text-amber-900">
            {last.feedback.map((f, i) => <li key={i}>{f}</li>)}
          </ul>
        </div>
      )}
    </>
  );
}

function TraitTrajectories({ rounds }: { rounds: GameRound[] }) {
  const [trait, setTrait] = useState<TraitCode>('HBW');
  const data = rounds.map((r, i) => ({
    round: i + 1,
    Player: r.player.meanTrueByTrait[trait] ?? 0,
    AI: r.ai.meanTrueByTrait[trait] ?? 0,
    Oracle: r.oracle.meanTrueByTrait[trait] ?? 0,
  }));
  return (
    <div className="mt-3 rounded-xl bg-white p-3 shadow-sm">
      <div className="flex items-center justify-between">
        <div className="text-xs uppercase tracking-wide text-gray-500">Mean true BV per round</div>
        <div className="flex flex-wrap gap-1">
          {TRAITS.map((t) => (
            <button
              key={t.code}
              onClick={() => setTrait(t.code)}
              className={`rounded-full px-2 py-0.5 text-[11px] font-medium ${
                trait === t.code ? 'bg-blue-500 text-white' : 'bg-gray-100 text-gray-600'
              }`}
            >
              {t.code}
            </button>
          ))}
        </div>
      </div>
      <div className="mt-2 h-48">
        <ResponsiveContainer width="100%" height="100%">
          <LineChart data={data}>
            <CartesianGrid strokeDasharray="3 3" stroke="#e5e7eb" />
            <XAxis dataKey="round" tickFormatter={(v) => 'R' + v} />
            <YAxis tickFormatter={(v) => Number(v).toFixed(2)} />
            <Tooltip formatter={(v) => (typeof v === 'number' ? v.toFixed(3) : String(v))} />
            <Legend />
            <Line type="monotone" dataKey="Player" stroke="#4f46e5" strokeWidth={2} />
            <Line type="monotone" dataKey="AI" stroke="#10b981" strokeWidth={2} />
            <Line type="monotone" dataKey="Oracle" stroke="#f59e0b" strokeWidth={2} strokeDasharray="6 3" />
          </LineChart>
        </ResponsiveContainer>
      </div>
    </div>
  );
}

// Per-round Δ in mean true BV across traits, for the Player. Antagonisms
// show up immediately as red/green pairs in the same row.
function TraitDeltas({ rounds }: { rounds: GameRound[] }) {
  if (rounds.length === 0) return null;
  return (
    <div className="mt-3 rounded-xl bg-white p-3 shadow-sm">
      <div className="mb-2 text-xs uppercase tracking-wide text-gray-500">
        Per-round trait response (Player Δ true BV)
      </div>
      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead className="text-xs uppercase tracking-wide text-gray-500">
            <tr>
              <th className="py-1 text-left">Round</th>
              {TRAITS.map((t) => (
                <th key={t.code} className="py-1 text-right font-mono">{t.code}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {rounds.map((r, i) => {
              const prev = i === 0 ? null : rounds[i - 1].player.meanTrueByTrait;
              return (
                <tr key={r.id} className="border-t border-gray-100">
                  <td className="py-1.5">R{i + 1}</td>
                  {TRAITS.map((t) => {
                    const cur = r.player.meanTrueByTrait[t.code] ?? 0;
                    const before = prev ? (prev[t.code] ?? 0) : 0;
                    const d = cur - before;
                    const colour =
                      Math.abs(d) < 0.01
                        ? 'text-gray-400'
                        : d > 0
                          ? 'text-emerald-600'
                          : 'text-red-600';
                    return (
                      <td key={t.code} className={`py-1.5 text-right tabular-nums ${colour}`}>
                        {d >= 0 ? '+' : ''}
                        {d.toFixed(2)}
                      </td>
                    );
                  })}
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
      <p className="mt-2 text-[11px] text-gray-500">
        Antagonisms show up as red/green pairs in the same row. With r<sub>g</sub>(HBW, WSSV) ≈ −0.6, a strong green on HBW often pairs with red on WSSV.
      </p>
    </div>
  );
}

function Score({ label, v, colour }: { label: string; v: number; colour: string }) {
  return (
    <div className="rounded-md bg-white p-2 shadow-sm">
      <div className="text-[11px] uppercase tracking-wide text-gray-500">{label}</div>
      <div className={`text-lg font-bold tabular-nums ${colour}`}>${v.toFixed(2)}</div>
    </div>
  );
}

function cumulative(rounds: GameRound[], upto: number, who: 'player' | 'ai' | 'oracle'): number {
  let s = 0;
  for (let i = 0; i <= upto; i++) s += rounds[i][who].meanTrueIndex;
  return s;
}
